options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: go-modules
      path: /go
  env: ["GOPATH=./tdsschedules"]

steps:
  - id: go_version
    name: "gcr.io/cloud-builders/go:1.22"
    entrypoint: "ls"
    args: [ "-a", "-l" ]

  - id: go_test
    name: "gcr.io/cloud-builders/go:1.22"
    args: [ "test" ]

  - id: go_build
    name: "gcr.io/cloud-builders/go:1.22"
    args: [ "build", "-ldflags", "-s -w" , "-o", "hello-app", "./" ]

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/hello-app:latest', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/hello-app:$SHORT_SHA', './hello-app/' ]

  - id: docker_push
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/hello-app:$SHORT_SHA' ]
