options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: go-modules
      path: /go
  env: [ "GO111MODULE=auto", "GOPATH=/go"]

steps:
  - id: go_build
    name: golang:1.23
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go install github.com/jstemmer/go-junit-report/v2@latest
        2>&1 go test -timeout 1m -v ./hello-app | /go/bin/go-junit-report -set-exit-code -iocopy -out ./hello-app/${SHORT_SHA}.junit.xml

  - id: docker_build
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/hello-app:latest', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/hello-app:$SHORT_SHA', './hello-app/' ]

  - id: docker_push
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/hello-app:$SHORT_SHA' ]
